### ISSUE TITLE
Various 1.8 crafting recipes.

### ISSUE THREAD

**Issue by mibby** [NavidK0/Carbon#3]
@NavidK0 Here's a list of 1.8 recipes.
✓ = Implemented and 100% functional, bug free.
--- = Partially implemented, buggy.
✗ = Not implemented.
- [✓] Diorite (Crafting recipe: 2 cobblestone and 2 Nether quartz in a checker board pattern)
- [✓] Polished Diorite (Crafting recipe: 4 diorite in a 2x2 configuration)
- [✓] Andesite (Crafting recipe: 1 cobblestone and 1 diorite)
- [✓] Polished Andesite (Crafting recipe: 4 andesite in a 2x2 configuration)
- [✓] Granite (Crafting recipe: 1 Nether quartz and 1 diorite)
- [✓] Polished Granite (Crafting recipe: 4 granite in a 2x2 configuration)
- [✓] Coarse Dirt (Crafting recipe: dirt and gravel in a 2x2 checkered pattern, yields four coarse dirt)
- [✓] Red Sandstone (crafted with 4 red sand in a square)
- [✓] Red Sandstone Slabs (crafted with 3 red sandstone in a line)
- [✓] Smooth Red Sandstone (crafted with 4 red sandstone in a square)
- [✓] Chiseled Red Sandstone (crafted with 2 red sandstone slabs on top of each other)
- [✓] New Door Types
- [✓] New Gate Types 
- [✓] New Fence Types (and new crafting recipe)
- [✓] Iron Trap Door 
- [✓] Iron Door 
- [✓] Slime Block (crafted with 9 slimeballs in a grid)
- [✓] Prismarine (crafted with 4 prismarine shards in a square)
- [✓] Prismarine Bricks (crafted with 9 prismarine shards in a grid)
- [✓] Dark Prismarine (crafted with 8 prismarine shards surrounding an ink sac in the middle)
- [✓] Sea Lantern (crafted with 4 prismarine shards in the corners, rest prismarine crystals)
- [✓] Rabbit Stew
- [✓] Moss Stone (Craftable from one cobblestone and one vine)
- [✓] Mossy Stone Bricks (Craftable from one stone brick and one vine)
- [✓] Rabbit Hide -> Leather (crafted in a 2x2 arrangement to produce leather)
- [✓] Cracked Stone Bricks (Obtained by smelting stone bricks)
- [✓] Red Sandstone Stairs (crafted with 6 smooth red sandstone in a stair pattern)
- [✓] Chiseled Stone Bricks (Craftable from two stone brick slabs on top of each other.)
- [---] Banners (No sway on old worlds.)
- [---] Armor Stands

**Comment by NavidK0** [comment]
Yes, I can fix this. Looks like the cobblestone wall recipes are also missing.

**Comment by NavidK0** [comment]
I will fix this as soon as I get home.

**Comment by mibby** [comment]
@NavidK0 Updated first post with what recipes are now working and implemented as of this commit.
https://github.com/NavidK0/Carbon/commit/0da8f35147fc1efd4dec38482b1917617485f908

However;
- [---] Cracked Stone Bricks (Obtained by smelting stone bricks)

is broken. Stone bricks are smelting, but smelting into mossy stone brick instead of cracked.

**Comment by NavidK0** [comment]
Oops, that's just a typo on my part. Fixed.

**Comment by mibby** [comment]
Cracked stone brick confirmed fixed. Updated post with what is implemented and working. Two more recipes to go outside of armor stands and banners!

**Comment by Shevchik** [comment]
Recipe list needs to be rechecked now because of the new recipes fix applied.

**Comment by mibby** [comment]
@Shevchik Checked all recipes again. Updated first post.
- [---] Polished Diorite (Crafting recipe: 4 diorite in a 2x2 configuration)
- [---] Polished Andesite (Crafting recipe: 4 andesite in a 2x2 configuration)
- [---] Polished Granite (Crafting recipe: 4 granite in a 2x2 configuration)

All create stone brick instead of polished variant.
- [---] Red Sandstone Slabs (crafted with 3 red sandstone in a line)

Creates red sandstone slabs, but they no longer function like half slabs. Not stackable, acts like whole blocks.

Recipes that rely on vanilla material, such as stone and torches, can be used in other recipes that are not part of 1.8. (In other words, the bug that broke recipes that relied on stone a while back, does not exist. Cobblestone can also be smelted into stone blocks that stack, not stuck on 1 block.)

Everything else not marked has not been implemented yet.

Did however notice this. Typed the Essential's command '/recipe [item]' and noticed checkered boxes for some recipes. The crafting recipes work fine normally when crafting yourself, just the essential's recipe command is not showing the correct material.

![link](http://i.imgur.com/qbJcRQS.png)
![link2](http://i.imgur.com/l3UJVl9.png)

**Comment by Shevchik** [comment]
Will check this.

**Comment by Shevchik** [comment]
Fixed it

**Comment by mibby** [comment]
Updated first post. Compiled source as of commit https://github.com/NavidK0/Carbon/commit/9a8af274f2dfcdf08e90643073ee505fdafea75e

Polished stones are correctly being made again.
- [---] Red Sandstone Slabs (crafted with 3 red sandstone in a line)
  Still acting as a whole block instead of half slabs.

Recipes showing IDs for vanilla blocks (not 1.8) are still broken. It is for every ID that relies on wood or torches. Recipes reinjected in Carbon such as doors, gates, and fences, all fine. But older recipes such as beds, boats, chest, workbench, etc. all purple textured. Removing carbon, all are perfectly fine.

**Comment by mibby** [comment]
I also found the issue with red sandstone stairs.
- [---] Red Sandstone Stairs (crafted with 6 smooth red sandstone in a stair pattern)

You have it implemented, but mising some recipes. You have it defined as 6 red sandstone blocks in a stair pattern creates red sandstone stairs, but you should be able to use any of the 3 sandstone variants to craft stairs. Red sandstone, smooth red sandstone, and chiseled red sandstone.

**Comment by Shevchik** [comment]
Recipes work fine for me. No emo textures. Can you please make screenshots of your problem?

**Comment by mibby** [comment]
The crafting recipe is fine. What isn't fine is plugins that display recipes or use the vanilla ID for wood/torches in GUIs. For example, Essential's '/recipe' command. Anything reinjected from Carbon is being displayed wrong. Screenshots are provided above.

**Comment by NavidK0** [comment]
I see that... hmm... all the custom recipes work fine.

But the ones that are replaced in Blocks are showing odd textures.

**Comment by NavidK0** [comment]
I'm not sure what causes that, but the names are correct.

**Comment by Shevchik** [comment]
Probably those are wildcard recipes. They return 32768 as data when converting to bukkit recipe  and that displays wrong in gui.

**Comment by Shevchik** [comment]
Fixed red sandstone slabs and stairs.
Fixed chiseled bricks.

P.S. Can't reproduse essentials recipe bug, wat version of essentials do you use?

**Comment by mibby** [comment]
Essentials #Dev2.14.98.
http://ess.ementalo.com/project.html?projectId=Essentials

**Comment by mibby** [comment]
Updated first post with what's working as of commit https://github.com/NavidK0/Carbon/commit/f92cf31877df11b6cb0701ac1efdcbe3d9524a9d

Noticed some early banner commits. Tested banners, still not craftable or placeable.

**Comment by mibby** [comment]
@Shevchik Testing banners as of commit https://github.com/NavidK0/Carbon/commit/e39e7144571983d4cebd854a5cebf5b3cf38c8fe

Can spawn in basic banners in creative, but none of the dye recipes are functional. Also the basic crafting recipe for banner stands are not functional yet.
http://minecraft.gamepedia.com/Banner

**Comment by mibby** [comment]
@NavidK0 Compiled source as of commit https://github.com/NavidK0/Carbon/commit/b12723468822b0bd909ff07552b5a8774fee13a9

Banners are now craftable, except wool color recipes are messed up.
- White wool creates black banner.
- Pink wool creates cyan banner.
- Red wool creates orange banner.
- Black wool creates white banner.
- Gray wool creates light gray banner.
- Light gray wool creates gray banner.
- Cyan wool creates pink banner.
- Purple wool creates lime banner.
- Blue wool creates yellow banner.
- Brown wool creates light blue banner.
- Green wool creates magenta banner.
- Orange wool creates red banner.
- Magenta wool creates green banner.
- Light blue wool creates brown banner.
- Yellow wool creates blue banner.
- Lime wool creates purple banner.

All dye recipes are also still not functional.
http://minecraft.gamepedia.com/Banner

**Comment by NavidK0** [comment]
Dye recipes will not be functional for 1.6, but it's planned for future versions. I know about the wool color recipes though, I'm trying to fix that now.

**Comment by mibby** [comment]
Updated as of commit https://github.com/NavidK0/Carbon/commit/dc51d309932e4ebd22f0d94b9af2932c798e78ad

Armor stands are not craftable yet and still have some odd bugs (such as leg standing up).
Banners seem to be nearly 100% implemented. Just don't sway on 1.7 server worlds.

**Comment by Shevchik** [comment]
Armor stand recipe added. It should be the last recipe. Just need to make stupid banners sway, maybe i misscalculated something.
